#!/usr/bin/env bash

if [[ "$(docker images -q gopher-eye-server 2> /dev/null)" == "" ]]; then
    echo "Docker image 'gopher-eye-server' not found. Building..."
    docker build -t gopher-eye-server .
fi

docker run -v $(pwd)/app:/app -v /mnt/s3-gopher-eye/plants:/app/plants -v /mnt/s3-gopher-eye/images:/app/images -v $(pwd)/models:/app/models -v /mnt/s3-gopher-eye/trials:/app/trials -p 127.0.0.1:5000:5000 -d gopher-eye-server